### ISSUE TITLE
Change video quality

### ISSUE THREAD

**Issue by KennedyTedesco** [vimeo/player.js#10]
Hi there! It's gonna be possible to change the video quality? This would be greatly appreciated.

**Comment by bdougherty** [comment]
We have no plans to add quality switching to the api at the moment. It would be helpful to know what your use case is for future consideration though.

**Comment by KennedyTedesco** [comment]
Got it. Mainly to use with projects such this one: https://github.com/Selz/plyr

**Comment by stefan-hausmann** [comment]
I'd like to +1 this.

At the moment, the player API allows us to control all aspects of the existing Vimeo player, e.g. volume, video seek position, play/pause etc.
So we could (and some of us even want to ;-)) provide our own player controls (and therefore hide the default seekbar, volume, logo etc.). One reason for that: maybe we have additional gui elements and because the default controlbar cannot be styled / positioned other than at the bottom of the video display, we need our own controlbar to combine both standard player gui and our own extended gui.

But the only thing that's currently not available via API is to display current video stream quality and change it via our own controls (and also Fullscreen functionality, but this can be solved by using HTML5 fullscreen API ourselves).

So would it be feasible to add another "qualityChanged" event and "currentQuality"/"availableQualities" properties?

Would be great!

**Comment by bdougherty** [comment]
@stefan-hausmann if you're looking to do lots of customization like that, I think using the third-party player urls (provided on the settings page for PRO members) and your own player is your best bet.

**Comment by stormrockwell** [comment]
definitely, +1 to this.

This is being used for a hero video on my end with a width of 1028. Without the feature, it seems to default to 360

**Comment by hootlex** [comment]
This is useful when you want to _remember_ users' selected resolution when they watch more than 1 videos. When people are on mobile it's likely that they choose to watch in low resolution so they don't spend a lot. By resetting the resolution when they navigate to another page/video they have to manually reduce the resolution every time.

**Comment by levydavidarg** [comment]
Hi, I would like to give users the option to determine whether to use High bandwidth or Low bandwidth.
This makes sense for people using their 3g / 4g connection with a limited amount of monthly traffic.

This way we care about people's expenses.
Any chance I can create a toggle button for Highest and lowest quality?
