### ISSUE TITLE
`player.loadVideo()` sometimes freezes the video playback

### ISSUE THREAD

**Issue by obber** [vimeo/player.js#1024]
### Expected Behavior

I expect `player.loadVideo(ID)` to play `ID` without issue once it's loaded.

### Actual Behavior

Video `ID` will begin playing but freeze in the middle of playback.

### Steps to Reproduce

I've recorded a loom of me reproducing this with a bit more context here: https://www.loom.com/share/e13b15c651d549e884d7c41db83c305f

1. Clone this minimal reproduction repository: https://github.com/obber/vimeo-playback-issue-sandbox
2. CD to the root directory of the repo. 
3. Run `npm i`
4. Run `npm start`
5. Navigate videos using the forwards / back button (in no particular pattern, at least that I've observed)
6. Observe that the video will freeze sometimes for some videos.

Thanks for investigating! Any direction or guidance would be really appreciated :)

**Comment by KevinWilson-Linney** [comment]
I am experiencing the same issue. 

We have a set of 5 videos. Intermittently, one of the videos will load and not start streaming any data.

**Comment by kaeruB** [comment]
I have a similar issue that might be related to `loadVideo` function.
I also have a set of videos.

The problem on my website is as follows: 
After switching between videos and clicking the back button in the browser, I always get:
`Hey There! To play your video here, change its privacy settings so it can be embedded on: player.vimeo.com`
or
`Sorry Because of its privacy settings, this video cannot be played here.`
![image](https://github.com/vimeo/player.js/assets/33574996/1bda9a72-5c28-4c23-9087-327bca280088)
![image](https://github.com/vimeo/player.js/assets/33574996/93b80358-c367-4c40-a141-d2f432d5d705)

**You can also see that type of error on the video that is provided in the issue description as well.**

I tried to add "[player.vimeo.com](http://player.vimeo.com/)" to allowed domains and the privacy errors disappears, but  hitting the browser's back button still blocks loading any different video on the website.
The behavior is as follows:
1. click the back button
2. click any other video from a list of videos
3. the player doesn't load a different video, plays the same one 

Also, I see this in the console after adding the domain:
![image](https://github.com/vimeo/player.js/assets/33574996/f0942d9d-406b-44da-8aea-6119bb5a514b)

Some of my thoughts:
* adding the "[player.vimeo.com](http://player.vimeo.com/)" domain to allowed domains is not necessary since it worked fine before without adding it (and we do not want to set it globally)
* the suspect is `loadVideo` function

Our project uses the latest version of the library @vimeo/player": "2.23.0".

**Comment by kaeruB** [comment]
One more comment that might be useful in the investigation - here is a healthy request example when there is no problem with loading a video:

![image](https://github.com/vimeo/player.js/assets/33574996/f08c338e-bf98-49a6-84a3-d2424c3887e7)


 and here is a request when the privacy error happens: 

![image](https://github.com/vimeo/player.js/assets/33574996/4b1ae9c9-c2f6-4075-b861-086fcce6e707)

You can see that Content-Security-Policy part is different.

**Comment by rkrishnan8594** [comment]
Hey all - thanks for reporting these issues and your patience in awaiting a response.

@obber @KevinWilson-Linney  - Thanks for providing a screen recording and a demo environment. Unfortunately, though, I'm not able to reproduce the issue in which playback freezes partway through the video. Is this issue still occurring for you? If it is, can you [contact support](https://vimeo.com/help/contact) on vimeo.com? This would be an issue with the underlying player, not the Player.js library.

@kaeruB - I think the issue you're encountering, in which you see a privacy error upon hitting the back button, is different than the OP's. The reason why you encounter a privacy error in his example is because one of his videos has a domain restriction, so it's being correctly blocked. That being said, I believe your issue matches an existing issue that has been reported, so I'm going to leave this thread open for further discussion. Can you share an example page where your issue can be reproduced?

**Comment by KevinWilson-Linney** [comment]
@rkrishnan8594 I believe this is still happening and I could replicate it with 2 of my colleagues at the time. What seems to happen is player.loadVideo() will load the video but sometimes it just does not auto-play. This issue only exists with auto-play as if you present the controls the user will manually be pressing play.

**Comment by rkrishnan8594** [comment]
I see. This sometimes occurs when the browser auto-pauses playback if the player is not muted. Can you please share a link where this issue can be reproduced?

**Comment by rkrishnan8594** [comment]
@kaeruB Sorry for the follow-up on this issue. It should now be fixed.

**Comment by kaeruB** [comment]
@rkrishnan8594 Than you for the fix! 🙇
