### ISSUE TITLE
Using chapter_id embed option with Javascript Player

### ISSUE THREAD

**Issue by jybleau** [vimeo/player.js#1039]
### Expected Behavior

Setting `chapter_id` option on new player should start the video at the corresponding chapter index.

Like this: 
```javascript
const player = new Vimeo.Player(div, {
      id: '969158456',
      autoplay: true,
      muted: true,
      responsive: true,
      chapter_id: 4
    })
```

As described here: https://developer.vimeo.com/player/sdk/embed#embed-options-as-objects

### Actual Behavior

Video starts at the beginning.

### Steps to Reproduce

https://jsfiddle.net/jybleau/goy0ku8x/

### Notes

The Player oembed.json GET request sees the `chapter_id` param and return the reference in the `html` property of the response object.
https://vimeo.com/api/oembed.json?url=https%3A%2F%2Fvimeo.com%2F969158456&id=969158456&autoplay=true&muted=true&responsive=true&chapter_id=4

Am I missing something...? Thanks.

**Comment by iangoodall** [comment]
Hi @jybleau , we had a similiar issue when we were trying to get videos to play from specific chapters, so we used code like below (just after you've started the player) and it works. Again, this may be a workaround but it does seem to work.

`    player.getChapters().then( function(chapters) {
    	player.setCurrentTime(chapters[chapterid].startTime)
    })`

**Comment by jybleau** [comment]
Hello @iangoodall good idea, using the chapter's startTime would do the trick for now. Thanks!

And the problem seems not to be in this repository, it would be in the "player" inside the iframe.

@bdougherty should I open a ticket directly with Vimeo support? Or you can handle it from here?

**Comment by rkrishnan8594** [comment]
Thanks @iangoodall for sharing your workflow.

@jybleau - the `chapter_id` that you provide must be the ID of the chapter object, rather than the index of the chapter in the list. Unfortunately, it's a bit tricky right now to get that chapter ID. The simplest way to do that would be to press the "Copy Link" button in the chapter row in the chapters menu, and then grab the ID off of the `#` param on the copied URL. We're looking at eventually adding a `chapter` parameter, though, for which you could provide an ID, index, or name, which would be simpler.

I'm going to close this ticket for now given that you've found a path forward.
