### ISSUE TITLE
Unable to get property 'bitrate' of undefined or null reference (MS Edge)

### ISSUE THREAD

**Issue by kKreics** [vimeo/player.js#119]
### Expected Behavior
During a video I should be able to swap it with a different one and be able to play it.
### Actual Behavior
While swapping videos I get an error: 
```
Unable to get property 'bitrate' of undefined or null reference.
```
### Steps to Reproduce
JSFiddle: https://jsfiddle.net/7kLnk9gt/7/
Run the JSFiddle in MS Edge on MS Windows 10.

**Comment by mark-cameron** [comment]
Was wondering if this issue is going to be fixed?

I have encountered this issue in both Edge 38 and IE 11.

Every second time I call `player.loadVideo(XXX)` with different ID's it has this issue and the player won't load the video. 

First tried a workaround where after calling loadVideo the first time I would wait 5 seconds, check the current time and if that was zero then call it again. This loaded the video - the audio was fine but the video was a mess and hadn't decoded properly.

Current workaround that I am using is to wait the 5 seconds and check if it playing, if not then load a different placeholder video and once that has loaded load the actual video. This seems to work but is not ideal.

**Comment by rsichel107** [comment]
This issue should have been resolved. Thank you for reporting.
