### ISSUE TITLE
get html5 video properties

### ISSUE THREAD

**Issue by albert025** [vimeo/player.js#269]
### Expected Behavior
get html5 video properties (played, seekable etc.)
### Actual Behavior
didn't provide Promise of those properties

**Comment by luwes** [comment]
@albert025 what problem are you trying to solve where you need these properties?

**Comment by albert025** [comment]
need to capture user activities for Google Analytic, to calculate the actual play time and seeking time.

**Comment by jybleau** [comment]
My use case: A training video where you don't want the user to seek forward (or seek to skip the video).

If you simply remove the player controllers, you can still seek forward on mobile devices when in fullscreen. And you have to code your own controls, which is sad because they already exists beautifully with the embed player.

I would use it to prevent seeking like in this HTML5 video example:
https://jsfiddle.net/jybleau/zes4hbdd/

Thanks

**Comment by luwes** [comment]
Closing in favor of #61, we're going to consider adding `video.played` and `video.seekable`. Will keep you posted in #61.
