### ISSUE TITLE
Passing a Query String Instead of Video ID to Vimeo.Player() Constructor

### ISSUE THREAD

**Issue by agrahn** [vimeo/player.js#275]
This is a feature request/enhancement

It would be nice if the Embed Options also accepted a search string to be passed to the Player constructor, letting the user select a video from a returned list of search results.

This is what the YouTube embedded player API provides via the `playerVars` properties `listType: "search"` and `list: "<search term(s)>"`

It would be nice if  the Vimeo player JS API would provide a similar thing.

**Comment by luwes** [comment]
@agrahn thanks for the request. I agree that it could be useful but it's a pretty specific use case that can easily be implemented in JS with a wrapper function around the `Vimeo.Player()` constructor.

We'll leave this issue open for a bit to gain interest but generally we like to keep the library small and lean.

**Comment by agrahn** [comment]
Thank you a lot  for your feedback, @luwes.

For example, in https://agrahn.gitlab.io/ABLoopPlayer/ I made use of this YT-API feature. If a query string was provided via the text input (instead of a video ID), then, after loading the player, there is an icon shown in the top left corner of the player that expands to a list of search results (20 items max.) if clicked. I think this is a useful feature. So, thank you once more and kind regards.

**Comment by luwes** [comment]
@agrahn thanks again for this feature request. After putting some more thought in this, such behavior will not be added in the foreseeable future because of the way the player is setup. Internally it doesn't have any concept of playlists and the player backend doesn't have a search feature.

I think this is definitely a nice idea for a third-party app which could use the Vimeo backend api's to achieve this.
