### ISSUE TITLE
Video player fullscreen playing behind Ionic 3 mobile app

### ISSUE THREAD

**Issue by sam-suresh** [vimeo/player.js#281]
I'm embedding the Vimeo video using iframe in Moodle LMS.

When viewing the page in Moodle Mobile app which is based on Ionic 2, the video loads fine in mobile app however when click full screen the video play behind the app and it cannot be seen.
Moodle developers said, this is Vimeo specific issue.

We tried to embed Youtube video and it can be played in fullscreen without any issue.

Is there any workaround for Vimeo to play in fullscreen in Ionic 3 Mobile apps?

**Comment by BluebambooSRL** [comment]
I have the same problem... did you found any solution?

**Comment by MayGo** [comment]
Had same problem with ionic 3.

ionic has class:
```
ion-app,
ion-nav,
ion-tab,
ion-tabs,
.app-root,
.ion-page {
    contain: strict;
}
```

**strict**
Indicates that all containment rules are applied to the element. This is equivalent to contain: size layout style paint.

**paint**
Indicates that descendants of the element don't display outside its bounds. If an element is off-screen or otherwise not visible, its descendants are also guaranteed to not be visible.

I removed paint from that list. And override that in my app.css

```
ion-app,
ion-nav,
ion-tab,
ion-tabs,
.app-root,
.ion-page {
    contain: size layout style;
}
```

**Comment by luwes** [comment]
@sam-suresh is this still an issue? we made some changes to the fullscreen functionality that could have resolved this.

**Comment by sam-suresh** [comment]
This is solved now.
Thanks

Sam
