### ISSUE TITLE
player.js and hidden from vimeo privacy settings not working

### ISSUE THREAD

**Issue by Ravenna** [vimeo/player.js#334]
### Expected Behavior
Video embeds successfully

### Actual Behavior
Video embeds but vimeo js fails to load the video

### Steps to Reproduce
embed a video that is hidden from vimeo and restricted to specific domains using the player.js

I have a business account, paying more than $500 a year and would like to be able to use the player js in a meaningful way.  I am loading videos via the player.js.  I want the videos hidden from vimeo and embeddable only on my domain as the videos are my IP.

Please advise ASAP

**Comment by jonascarlbaum** [comment]
We have the same issue, I presume.
We have no control over the customers videos, but I can confirm having the same issue on a video that can’t be viewed in Vimeo player directly due to privacy settings and the video can not be found in searches. The video plays on the site when embedded, but not on other sites.

So, without access I pressume we have the same issue.

I’m on the iPhone now, but I’ll try to give you the information from memory. Maybe not 100% accurate — but it’ll give you the basic info you need to start pinpointing the problem.

In our case the video embedded is at https://player.vimeo.com/video/ID and the player.js tries to access it by http(s)://vimeo.com/ID and that returns a 404. So there is probably some issue where the exact URL is important but the player.js assumes the later URL is valid in all cases, but I assume it’s not.

—

My assumptions might be wrong, but hopefully it can give you some angels to handle the issue.

**Comment by luwes** [comment]
@jonascarlbaum there is nothing we can do about that. you say you have no control over the customers videos and they chose to make it private. it's normal that you can't embed it on your website then because the customer has configured it that way.

**Comment by luwes** [comment]
@Ravenna can you check the `embed` tab and click the `embed code` button.
Some privacy settings require an extra hash on the vimeo URL.

Embed it like so

```js
<div id="made-in-ny"></div>

<script src="https://player.vimeo.com/api/player.js"></script>
<script>
    var options = {
        url: 'https://vimeo.com/293438045/463ebf7bcf'
    };

    var player = new Vimeo.Player('made-in-ny', options);

    player.setVolume(0);

    player.on('play', function() {
        console.log('played the video!');
    });
</script>
```

**Comment by jonascarlbaum** [comment]
Well, I mean I haven’t got the credentials to look at how they’ve set up their privacy settings. We are working on their site and I mean that the affected video shows as embedded IFrame on production, not on stage, so I just wrote that to give you the info that implies that setup.

We are actually using plyr (https://github.com/sampotts/plyr) that uses player.js. I need to look closer at this tomorrow.

I can of course ask the customer for the credentials to look things up or ask them to give me a screenshot of the privacy settings.

My initial look into the issue was that there might be a issue in player.js, but it might as well be how player.js is used by plyr.

**Comment by Ravenna** [comment]
Thanks @jonascarlbaum I will give this a shot later today.

**Comment by jonascarlbaum** [comment]
@ravanna guess you mean @luwes 😉

**Comment by ahmadawais** [comment]
I have the same issue. Making a course and want the videos to only be available via my website. When I hide from Vimeo and allow on my specific site I get this error.

```js

Failed to load resource: the server responded with a status of 404 (Not Found)
player.es.js:796 Uncaught (in promise) Error: “https://vimeo.com/297488944” was not found.
    at XMLHttpRequest.xhr.onload (player.es.js:796)
```
@luwes help? This renders hosting on Vimeo useless for private course. It was not like this a month ago.

**Comment by jonascarlbaum** [comment]
@ahmadawais error is the exact one I talked about (from memory).

**Comment by ahmadawais** [comment]
I was able to get it working. I have to chose `Hide from Vimeo` and then add my domain in the embeddable specific sites. No other options work. E.g. the private link option doesn't work.

**Comment by luwes** [comment]
Thanks for reporting guys. We're aware of the different behavior w/ direct iframe embeds compared to a player.js initialization via `id`.

When the `private link` setting is chosen our oEmbed api returns a 404 which shouldn't be the case, we are working to resolve this soon.

In the mean time you could use the `url` parameter instead of `id` taking in account you have to add the hash to the url. For example:

`https://vimeo.com/293438045/463ebf7bcf`

Notice the `id` comes first and is followed by this hash `463ebf7bcf` after the slash. Our oEmbed API will successfully return for this embed option.

**Comment by jonascarlbaum** [comment]
Great, so it’s solvable for me by instructing the customer to change some settings in Vimeo.

But still it should work for us in the first place without workarounds?

**Comment by jonascarlbaum** [comment]
Ah, answered @ahmadawais comment.

Seems I need to get access to their account to test and advice them correctly.

For example, we let them put in an `url` in the `cms`. We parse `url`:s to see if it is a valid `Vimeo` `url`. Then we parse the `id` as the last parameter in `path`. That is no longer valid I suppose. Some `url`:s they might provide could be with a trailing `hash` I suppose?

It’s great to hear that you are working on a solution. 👍

**Comment by luwes** [comment]
This should be resolved. Please let me know if you see otherwise or have any questions. Thanks.

whitelisted domain: https://codepen.io/luwes/pen/mzZgZg
not whitelisted: http://jsfiddle.net/luwes/y51d8f3b/
private link: https://vimeo.com/3198167/0048bd3378

**Comment by cdiem** [comment]
It seems that videos protected by private link (without domain protection) don't work.
Player.js gets 404 error from oEmbed API.

<img width="695" alt="screenshot 2019-02-27 at 19 10 22" src="https://user-images.githubusercontent.com/4948518/53504653-62ac3f00-3ac3-11e9-8b25-133aa0df0234.png">

<img width="375" alt="screenshot 2019-02-27 at 19 25 07" src="https://user-images.githubusercontent.com/4948518/53505700-735db480-3ac5-11e9-82ed-4c5581e241c8.png">

Here's the code:
https://codepen.io/cdiem/pen/ZPGvjZ

Link to the video: https://vimeo.com/320269670/eced817cc0
