### ISSUE TITLE
Player returns error when video page is loaded.

### ISSUE THREAD

**Issue by Gaurav-Bajpeyee** [vimeo/player.js#336]
### Expected Behavior
Video embeds successfully and returns the status and title of the video which is played.
### Actual Behavior
video embeds successfully but return error as 'You must pass either a valid element or a valid id.'
### Steps to Reproduce
Website Link: 'http://dawaipedia.com/hari_the_lion/#/login'
username: 'anil.pyplyn@gmail.com'
password: 'pass123'
path for player: after login->regualar class->Mathematics->Volume & Surface Area->Introduction
To check the error returned please right click on page and click inspect. check console tab for the error(Actually I am consoling the video title and status of the video, which will display in console immediately after loading video page). 
Code Snippets:
HTML : `<div id="vimeo_player"></div>`

Javascript: `var html = '<iframe src="'+$scope.course_video_data.video_name+'" id="course_video_player" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';
   document.getElementById('vimeo_player').innerHTML = html;
var iframe = document.querySelector('#course_video_player');
var player = new Vimeo.Player(iframe);

player.on('play', function() {
    console.log('played the video!');
});

player.getVideoTitle().then(function(title) {
    console.log('title:', title);
});`

**Comment by luwes** [comment]
could you try to log the result of
`var iframe = document.querySelector('#course_video_player');`

it seems to be failing this check

```
      if (!isDomElement(element)) {
        throw new TypeError('You must pass either a valid element or a valid id.');
      } 
```

**Comment by Tica7511** [comment]
I have the same issue, down below are my codes:
HTML:
 `<iframe src="https://player.vimeo.com/video/441206570" width="940" height="563" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>`

js:
<script src="https://player.vimeo.com/api/player.js"></script>
<script>
        var iframe = document.querySelector('iframe');
        var player = new Vimeo.Player(iframe);        

        player.on('play', function () {
            console.log('played the video!');
        });

        player.getVideoTitle().then(function (title) {
            console.log('title:', title);
        });
</script>

And I get the same error : Uncaught TypeError: You must pass either a valid element or a valid id.
and the error seems to cause on `var player = new Vimeo.Player(iframe);`
because I need to get the player who play the current time of the video and if he play above 70% of the video, it will update the db(sql server) and return a parameter to let me know that he almost fininshed the video.

Can anybody help me to fix this problem?
thanks.
