### ISSUE TITLE
Lazyloading iframe does not let me attach player event handlers

### ISSUE THREAD

**Issue by heenslice** [vimeo/player.js#398]
I am trying to lazyload a vimeo video but I am having some issues attaching event handlers to the vimeo player after the iframe has loaded.

I am using a script called lazy sizes to lazyload the iframe as it specifies in the docs

https://github.com/aFarkas/lazysizes

When the video is lazyloaded I am then initiating the vimeo player

Everything works as expected except I am unable to attach the vimeo event handlers to the new vimeo player?

However strangely if I add a settimeout before I try to attach the eventhandlers it works?

But I would prefer to not have to use a settimeout. I had hoped that adding the .ready().then() promise would ensure the video was ready before I attempt to attach the handlers.

### Expected Behavior

Player.on('play') & player.on('ended') events should attach to the video and fire when the video plays and ends.

### Actual Behavior

Player.on('play') & player.on('ended') events do not fire

### Steps to Reproduce

Here is a codepen example I have set up below.

https://codepen.io/heenac3/pen/moPZWx?editors=1010

**Comment by luwes** [comment]
@heenslice this was because of some issue in the lazysizes implementation.

If you use `data-src` that library will do the src injection automatically but it will remove the `src` attribute quickly after which would lead to a player.js error because it expects there to be a `src` attribute.

The problem was that you added your own injection which would lead to 2 player loads, the first one would have the event handlers but the second load didn't have them.

See here for a working example:
https://codepen.io/luwes/pen/oVZrdr?editors=1010
