### ISSUE TITLE
Video playback halting early after loadVideo() and play() while autoplaying

### ISSUE THREAD

**Issue by chellman** [vimeo/player.js#416]
### Expected Behavior

I'm trying to set up a playlist that, once playback starts, will just go right through videos in sequence until stopped.

### Actual Behavior

After the first video completes, the second video loads and plays, but playback stops right before the end, so the rest of the videos never load.

The console message "Vimeo ended event fired" only appears once, when the first video ends.  The second video gets very close to the end, but never makes it.  I've seen in #34 that this used to be an issue in the player itself, but I'm wondering if my approach is the problem here.

### Steps to Reproduce

Here's a fiddle.
https://jsfiddle.net/y5wo14ue/2/

I just searched vimeo.com for videos 30 seconds or less so I can test the events firing as easily as possible - the actual videos will be private videos locked to embedding on a Vimeo Pro user's website, if that makes any difference.

**Comment by kodabb** [comment]
the video used in the fiddle is https://vimeo.com/74345276 and the related manifest is https://skyfire.vimeocdn.com/1556560905-0x985cc05dbbacddd494d24a0b9d6341431831f50e/74345276/sep/video/189321005,437441895,437441896/master.json?base64_init=1

as you can see, the clip has 4 videos attached to it, due to a replace happened years ago, two from the earliest version and two from an older version. The older version has a completely different duration.

For some reason the client (app? player?) is making skyfire requests with a video id from the older set of transcodes, with three video streams instead of two. Since the duration of 189321005 is different than the other two, playback is interrupted as soon as the shortest stream ends (as expected).

When using the correct manifest (https://skyfire.vimeocdn.com/1556560905-0x985cc05dbbacddd494d24a0b9d6341431831f50e/74345276/sep/video/437441895,437441896/master.json?base64_init=1) the duration matches, so it should work correctly in that case.

**Comment by chellman** [comment]
Thanks, @kodabb. I just tried this with some new test videos I uploaded myself, and it is working as expected.

https://jsfiddle.net/xbcd6aen/

I'm not sure if this issue should stay open for the the case of dealing with old manifests, so I won't close it.
