### ISSUE TITLE
embedded vimeo player doesn't play till double click on the video

### ISSUE THREAD

**Issue by poussy** [vimeo/player.js#450]
On chrome latest version, for some clients, the embedded vimeo video doesn't get played till we double click on the video itself, but works fine on firefox.

**Comment by luwes** [comment]
@poussy do you have a test page online? 
we haven't heard any reports for Chrome

**Comment by poussy** [comment]
The issue was at the auto play flag of chrome , it has to be without user
gesture.

**Comment by luwes** [comment]
yes, this is normal with the new autoplay policies in Chrome.
the only thing you can do to be sure that the video will autoplay is to add the `muted` param.

thanks for your feedback.

**Comment by lthoa1807** [comment]
I have applied the muted on embed code and it works well on Mobile (when playing video, it will show a button 'tap to unmute'). But on the desktop, we can not unmute the video.
I add the embed code on squarespace site.
Do you have any advice?

**Comment by mikeyfe6** [comment]
if it only occurs on mobile its because of the autoplay/mute browser restriction on most of the modern webbrowsers... i've run into the same issue, went crazy and finally found a sollution... what worked for me was to manipulate the volume in my "play"-function.. turn the volume down and up at the same time...

like so; 
```
Vimeo.Player.setVolume(0);
Vimeo.Player.play();
Vimeo.Player.setVolume(1);

```
Also dont forget to add a useref or some of that kind to make sure this code above only fire once while pressing the play button...

heres where i use it; https://github.com/mikeyfe6/keepitreal/blob/master/src/components/layout/hero.tsx

PS; english is not my first lang.. sorry for the misspellings if there are any :)
