### ISSUE TITLE
Playback rate changing is not working

### ISSUE THREAD

**Issue by ivoneug** [vimeo/player.js#465]
### Expected Behavior
Should be able to set playback rate when controls are disabled.

### Actual Behavior
setPlaybackRate rejects when main controls are disabled.

### Steps to Reproduce
I'm setting the embed options into { speed: true, controls: false }, then I'm calling player.setPlaybackRate(0.5) and promise rejects with the message "Error: Setting the playback rate is not enabled for this video.".
We have a business account and this issue really annoying us :(
Hope you will fix it soon.

**Comment by fisherinnovation** [comment]
Thanks for your report! I agree, this seems like a annoying issue - we will reivew this internally and get back to you as soon as possible with a solution.

**Comment by jpdupere** [comment]
It also happens when the player is in background mode: { speed: true, background: true }

**Comment by ivoneug** [comment]
> Thanks for your report! I agree, this seems like a annoying issue - we will reivew this internally and get back to you as soon as possible with a solution.

Hi there, do you have any progress regarding this issue?

**Comment by steve52** [comment]
@ivoneug, sorry for the lack of updates here, but we have a PR for a fix that should be going out soon. Most likely tomorrow!

**Comment by ivoneug** [comment]
Hi guys! Do we have any news about this issue?
Looks like in the current version of Vimeo player (2.10.0) the playback rate changing feature is working now, but only for the first player created. If we destroy the player and create a new one - this feature doesn't work anymore.

**Comment by superfunkminister** [comment]
Hey @steve52, any updates on this?

**Comment by luwes** [comment]
@ivoneug are you sure this is not working? 
seems to be working on my end, https://codepen.io/luwes/pen/JjdReLG

it's probably because speed is not enabled in the embed settings.

<img width="417" alt="Screen Shot 2020-02-20 at 1 38 55 PM" src="https://user-images.githubusercontent.com/360826/74967185-80666880-53e6-11ea-856b-6dad689d7450.png">

thinking about it, I agree it's a bit confusing. needing it to be enabled in 2 places.

**Comment by superfunkminister** [comment]
You can only enable speed controls on the pro account anyway :-(

The error is caught in Chrome but in Firefox it crashes my whole Gatsby app in development mode.

**Comment by vojtad** [comment]
We also hit this issue. We would like to be able to call `setPlaybackRate` using Player API for videos with Playback controls hidden in Embed settings.

When I call `setPlaybackRate` with controls disabled I get this error:
```
Setting the playback rate is not enabled for this video.
```

However, I have set `speed: true` when creating the embed. Could you please look into this? We have Vimeo Premium account.

**Comment by fisherinnovation** [comment]
@vojtad Could you provide a link or example code we could take a look at the replicates your issue?

**Comment by vojtad** [comment]
Unfortunately I am not. I've managed to work around this just a couple of hours ago. Here are the steps I took, hopefully it will help you identify the issue:

1. I went to Embed preset settings (at `https://vimeo.com/settings/videos/embed_presets/<preset id>`) and check **Show play bar**, check **Speed control** and then uncheck Show play bar.
2. Then I checked ** Also apply to all existing videos** and saved changes.

After some time changing playback rate for all videos started working. I guess it took some time to apply new settings to all our videos.

It looks like **Speed control** affects the videos even when it is hidden because of unchecked **Show play bar**.

Here is a screenshot form before when it didn't work:
![before](https://user-images.githubusercontent.com/223731/86612888-132c2c00-bfb1-11ea-9020-029b2c0b3ce9.png)

Here is a screenshot for video where it works now:
![now](https://user-images.githubusercontent.com/223731/86612900-19220d00-bfb1-11ea-849c-64482d48e6b7.png)

Notice the Speed controls checkbox being in a different state although it is disabled.

**Comment by vocationeers** [comment]
As I have the same issue, here is an example:

`<html>
<head>
</head>
	<script src="https://player.vimeo.com/api/player.js"></script>
	<script>
		
	</script>
</head>
<body>
	<iframe id="vimeo" src="https://player.vimeo.com/video/436408894?background=1&autoplay=0" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
	
	<button onclick="vimeoapi=new Vimeo.Player('vimeo');vimeoapi.play()">Play</button>
	<button onclick="vimeoapi=new Vimeo.Player('vimeo');vimeoapi.play();vimeoapi.setPlaybackRate(0.5)">Play double speed</button>
</body>`

**Comment by fisherinnovation** [comment]
@vojtad I beleive the issue you were encountering is fixed. Could you please test again when you have a moment?

**Comment by wesbos** [comment]
I'm getting this issue again @fisherinnovation. Can't set playbackSpeed via the API.

**Comment by brunohbrito** [comment]
@wesbos Me too. Our platform start to get this response from API today.

Something has changed?

**Comment by luwes** [comment]
thanks for the feedback, today Vimeo launched speed controls for everyone so there's probably something that was missed. Sorry for the inconvenience. is this a straight iframe embed or via a DIV javascript embed? 

The api demo uses the iframe embed and still works
https://player.vimeo.com/api/demo

So I think it must be something with the oEmbed api then. We'll look into this very soon. Keep you posted.

**Comment by brunohbrito** [comment]
I'm using it with a div:

```html
 <script src="https://player.vimeo.com/api/player.js"></script>
 // ... 
<div id="videoPlayer" data-vimeo-defer data-vimeo-autoplay="true" data-vimeo-autopause="true" data-vimeo-url="@VideoUrl"></div>
```
The video itself not showing any control to change speed:
![image](https://user-images.githubusercontent.com/7241156/112415795-43fcee80-8d03-11eb-9d8f-957b07e0ee5b.png)

Although this option used to be there, there is another control at page where our users are able to control theses settings. Then this custom controls are using vimeo API:

```js
    var player = new Vimeo.Player('videoPlayer');
    player.ready().then(function () {
        player.setPlaybackRate(localStorage.getItem('playerSpeed'));
    });

    $('#videoSpeed').on('change', function () {

        player.setPlaybackRate(this.value);
        localStorage.setItem('playerSpeed', this.value);
    });
```

But when it occur the error described at this issue happens:

![image](https://user-images.githubusercontent.com/7241156/112416375-54619900-8d04-11eb-830c-c3162de7c5e4.png)

(Error: Setting the playback rate is not enabled for this video)

**Comment by wesbos** [comment]
@luwes Thanks, I'm using a div to embed my videos as well.

**Comment by brunohbrito** [comment]
@luwes 

It's fine now! 

thanks!

**Comment by fisherinnovation** [comment]
Thanks for the quick feedback everyone!
