### ISSUE TITLE
playProgress no longer working

### ISSUE THREAD

**Issue by makeyDev** [vimeo/player.js#477]
### Expected Behavior
Have a function trigger after 1 second of video playing

### Actual Behavior
It was working fine for months, stopped working without any changes to code

### Steps to Reproduce
Here is the code that is in use

`<div class="bannerOverflow"`
`    style="background-image:url({{ preview_image }})">`
`    <iframe id="vimeoIframe" style="opacity:0;" src="https://player.vimeo.com/video/{{ final_vimeo_code }}?autoplay=1&loop=1&autopause=0&muted=1&api=1" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen allow=autoplay></iframe>`
`    <div class="filter" style="background-image:url(https://cdn.shopify.com/s/files/1/0162/8612/files/filter.png?3590755423249765699);">`
`</div>`
`</div>`

`<script src="https://player.vimeo.com/api/player.js"></script>`

`<script>`

  `$('.bannerOverflow iframe').attr('style', 'opacity:0;');`

 ` var iframe = document.querySelector('#vimeoIframe');`

 ` var player = new Vimeo.Player(iframe);`

	
 ` player.on('playProgress', function(e) {`

   ` console.log('test');`

  `  if ((e.seconds * 1) > 0.5){`

  `    $('.bannerOverflow iframe').attr('style', 'opacity:1;');`

 `   }`

 ` });`

`</script>`

The video loads but the playProgress event never triggers anymore, doesn't even trigger console.log

can be seen on live site makeymakey.com homepage.

**Comment by fisherinnovation** [comment]
Thanks for reporting. This issue is due to the old v1 Player API no longer being in service. 

See https://github.com/vimeo/player.js/blob/master/docs/migrate-from-froogaloop.md for a detailed outline of how to ensure everything is up to date on your end.

Here is an example of using the `timeupdate` event, something that should help get everything working on your end again. https://jsfiddle.net/1rLfp7x4/
