### ISSUE TITLE
live stream on ios not show current time

### ISSUE THREAD

**Issue by zerohk123** [vimeo/player.js#503]
vimeo live stream on ios not show current time
it a bug ? or i have going to vimeo setting do some setup ?

**Comment by fisherinnovation** [comment]
Due to some technical restraints we have opted to not display the current time on live streams when viewed on iOS web playback. 

I will submit your feedback in our internal feedback pipeline as I do agree it would be very helpful to ensure this is displayed in all playback senerios. 

Thanks for ticketing!
