### ISSUE TITLE
Safari player stuck when history back used

### ISSUE THREAD

**Issue by nextend** [vimeo/player.js#574]
### Expected Behavior
You should be able to play the video.

### Actual Behavior
Spinner loads and there is a console error -> Invalid state error: The object is in an invalid state

### Steps to Reproduce
1. Open https://smartslider3.com/bugs/webkit/vimeo/ in Safari [OSX]
2. Play the video
3. Click on "Go to index2"
4. Use the browser back button or click on "Go black"

This error happens without the player api too, so it might be a Vimeo core bug.

Screen recording: https://www.youtube.com/watch?v=MzxQUfG0Z9s

**Comment by squareclouds** [comment]
i am having similar issues. when changing the src attribute of the iframe (for example lazy loading in reveal.js) the vimeo script adds a history entry. this means, if you pass 4 videos in a slider (or revealjs in my case) you have to hit back 4 times, because 4 extra history entries were added. i hope vimeo finds a solution for this...

**Comment by luwes** [comment]
looks like Safari fixed this bug 🎉
