### ISSUE TITLE
player.vimeo.com lacks IPv6 support

### ISSUE THREAD

**Issue by ikomwrestling** [vimeo/player.js#612]
player.vimeo.com lacks IPv6 addresses and thus resources (JavaScript) from it can't be received using IPv6.

Since the CDN seems to be served by Fastly, which has great IPv6 support, it should hopefully be a simple fix by asking Fastly support to enable IPv6 on the map, as per their [IPv6 documentation](https://docs.fastly.com/en/guides/ipv6-support).

Thank you.

**Comment by huaracheguarache** [comment]
Could that lift please be considered now? It's 2023 and [Google's IPv6 adoption statistics have surpassed 40%](https://www.google.com/intl/en/ipv6/statistics.html). Some countries have even introduced laws requiring the public sector to use services that support IPv6. You could end up losing clients due to your lack of IPv6-support.

**Comment by huaracheguarache** [comment]
I see that @luwes is not with Vimeo anymore, so I'm tagging @rkrishnan8594 as I've seen you respond in other issues.
