### ISSUE TITLE
Slow launching 

### ISSUE THREAD

**Issue by ALNAshef** [vimeo/player.js#614]
Hello, If the video is longer than 10 minutes, we're facing two problems:
1- The first problem is the synchronization between Audio and Video.
2- The second problem is that after pressing the play button there's a delay with playing the video.
Please notice that we are using API.

https://www.ontrainers.com/Temp/index.html

**Comment by luwes** [comment]
thanks for the feedback @ALNAshef. 

1. I see the synchronization issue but we couldn't verify if it was caused in the original video or not.

I recommend you double check the source video and see if it's not the cause, if not try to re-upload because generally there are no sync issues with Vimeo videos longer than 10min.

2. this is quite normal because the video segments have to be loaded and it can take some time depending on your internet connection. you could mimic a preload by calling play() and when the promise resolved immediately after call pause(). this way the first part of the video should be loaded.

hope this helps.
