### ISSUE TITLE
Vimeo videos not load for more than 10sec and sometimes doesn't load

### ISSUE THREAD

**Issue by archanavmahesan** [vimeo/player.js#636]
### Expected Behavior
Vimeo player should load videos in less than 3sec.
### Actual Behavior
Vimeo videos don't load for more than > 10 seconds and sometimes doesn't load at all until you click pause and click play again.
### Steps to Reproduce
- Create a page with 10 Vimeo iframes.
- Check whether the videos are loading without any lag
We have more than 60 Vimeo videos embedded into one page of our site. These videos are taking more than 10secs to load or sometimes it doesn't load. Does anyone have any thoughts on why this would happen? Does anyone have a solution to this one?

**Comment by fisherinnovation** [comment]
Could you share example links to pages where you are encountering this issue?

**Comment by archanavmahesan** [comment]
Thanks for the reply, following is the URL affected. https://www.zimmermannwear.com/z-videos

**Comment by manafpm** [comment]
Hi @fisherinnovation , @luwes ,

Please, are there any updates on the above mentioned issue?

Thanks and Regards,
Manaf

**Comment by fisherinnovation** [comment]
Videos seem to be loaded as expected on https://www.zimmermannwear.com/z-videos however I do see the page attemps to load >40MB worth of assets on page load. I believe what you are encountering is slow video load times because all of the other assets on your site are attempting to load at the same time.

I would reccomend not loading so many players on to your page as opt to only load them in once the user interacts with the elemen, this way you are loading so much up front and improve load time for content that is attempting to be viewed.
