### ISSUE TITLE
Video is not buffering further after pausing video

### ISSUE THREAD

**Issue by hammad99885** [vimeo/player.js#757]
### Expected Behavior
when a user pauses the video, it should keep on buffering even video is paused. 

### Actual Behavior
when the user pauses the video buffering also stops. for example, I'm using getBuffered() to get buffered values of video. while playing it returns me buffered value before few seconds of the current time and after few points of the current time, the previously buffered data is also discard,ed and on pausing getBuffered only return to the point where videos have buffered before pausing

**Comment by bdougherty** [comment]
This sounds like everything is working as expected. We use the `MediaSource` API to play videos, so only a certain amount of the video ahead of the `currentTime` will be buffered, and data in the buffer before the `currentTime` can be cleared out at any time so that more can be added later (the browser only allows so much data to be in the buffer at any given time).

If I am misunderstanding, please feel free to re-open.
