### ISSUE TITLE
Change thumbnail picture of video from js

### ISSUE THREAD

**Issue by mpone** [vimeo/player.js#796]
Could you, please, explain, do we have an ability to change a thumbnail picture of video from js ? Maybe through the options or in some another way ? For example, in VideoJS (another player library) there is a player.poster(img) function, do you have something the same here ?

**Comment by fisherinnovation** [comment]
Since thumbnails are creator controlled settings on videos, you will need to use our API as an authenticated user to perform any updating to the configured thumbnail asset on a given video.

You could opt to display an element on top of the player depending on your embed configuration, but that would have to be controlled as an external asset to the player embed.
