### ISSUE TITLE
Events not firing after loading new video

### ISSUE THREAD

**Issue by GianlucaFiorini** [vimeo/player.js#843]
### Expected Behavior
events should fire when user interacts with it
### Actual Behavior
event loop not firing(ended,play,timeupdate)
### Steps to Reproduce
load a video and run .on(ended) event or time update, it works fine, now upload another video on the same iframe events stop firing, the get methods stll work, but the events dont.

**Comment by Ashleycoo** [comment]
+1 for this.

We have multiple videos, once the ended fires it allows the user to move on. For some reason, now on iOS devices the ended event only triggers for the first video loaded into an iframe. The video never seems to end, the end card which used to load, no longer does. Not sure what's changed.

**Comment by GianlucaFiorini** [comment]
i found out later if you .load the video by id it keeps working, but if you change the src of the iframe the instance of the player is lost, so you need to use the load function instead of changing the src atributte

**Comment by Ashleycoo** [comment]
Thanks! That worked. Although it's a completely different iframe that loads each time, letting the new one load then using load video causes the events to fire. Glad it's working, but now have a lot to update! Don't understand why its been working as is for almost 2 years and now it doesn't.

**Comment by bdougherty** [comment]
@GianlucaFiorini is correct. If you change the loaded page in the iframe by changing the `src`, you will need to create a new player object and add your listeners again.

This is because all communication is done via `postMessage`, so the new player that has loaded is unaware of anything outside the iframe. Using `loadVideo()` sends a message to that player and so it continues to be aware of the listeners.
