### ISSUE TITLE
Cannot started video on iPad using API

### ISSUE THREAD

**Issue by sampotts** [vimeo/player.js#87]
### Expected Behavior
`player.play()` should start video

### Actual Behavior
returns `Promise { status: "pending" }`

### Steps to Reproduce
- Head to https://jsfiddle.net/SamPotts/95dojsxq/1/ on an iPad (observed on iOS 10) 
- Click the play button which uses the API to start playback
- Nothing happens

**Comment by bdougherty** [comment]
The player should be firing an error in this case that you can catch on that promise. I'll take a look.

**Comment by chiefego** [comment]
Same problem here.

See example [here](http://dev.weiljones.com/videotest)

When using in Chrome in standard mode everything works fine but when switching to mobile emulator mode, the api stops working even though play is called from click event handler.

**Comment by jacoblindgren** [comment]
I'm encountering the same problem. Are some events (i.e. player.play();) not compatible on iOS?

**Comment by bdougherty** [comment]
@chiefego that's because unfortunately there's no other way for us to detect besides using the User Agent.

@jacoblindgren as noted [in the readme](https://github.com/vimeo/player.js#play-promisevoid-passworderrorprivacyerrorerror), calling `play()` to initiate playback does not work on iOS. Once play has been initiated the first time by a direct input on the player, `play()` can successfully be used through the api.

**Comment by chiefego** [comment]
Hmmm, youtube api works fine on iOS.
see this https://webkit.org/blog/6784/new-video-policies-for-ios/

**Comment by jacoblindgren** [comment]
@bdougherty Thanks very much for the reply. At the risk of sounding naive: is there a button I can program that will imitate Vimeo's embedded play button that would count as the User Agent initiating play? The reason I ask is because in my scenario the embedded Vimeo video's play button is below something, causing it to be un-clickable/un-tappable.

**Comment by garrett-eclipse** [comment]
Following this as I'm experiencing the same issue and would like it to force autoplay on iOS.

**Comment by nashio** [comment]
I'm able to play on IOS fine using play(). Has anything changed?

**Comment by luwes** [comment]
This is fixed in the mean time. Let me know if you still have issues!
